package com.lfi.p3hd.demo.qr;

import com.lfi.p3hd.demo.utils.PreferencesUtil;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.TimeZone;

import okhttp3.OkHttpClient;

public class QRConfig {
    // Non-env-specific constants
    public static final String QR_TYPE                = "DYNAMIC";
    public static final String CURRENCY               = "AED";
    public static final String TERMINAL_ID            = "TERM001";
    public static final String TRADING_LICENSE_NUMBER = "TL-123456789";
    public static final String MERCHANT_CATEGORY_CODE = "5812";

    /**
     * Message identifiers the gateway validates against a fixed pattern.
     *
     * QA (Mithril 5.x) rejects a request without them; demo predates the field
     * and ignores it. Sending them on every env keeps one build working against
     * both — verified against both backends 2026-08-05.
     */
    public static final String QR_MESSAGE_TYPE_ID     = "cbdc.231.101.01";
    public static final String RETURN_MESSAGE_TYPE_ID = "cbdc.232.101.01";

    /** Fallback QR lifetime, used only when the response carries no timestamps. */
    public static final long QR_TIMEOUT_MS    = 300_000L;

    /**
     * How often to ask whether the QR has been paid.
     *
     * Was 5 s, which is fine for merely reporting a sale but not for acting on one:
     * the whole pre-settlement cancel window is about ten seconds from the payment,
     * so every second of polling lag is a second the operator loses. A 5 s interval
     * burned over half the window before the success screen even appeared. See
     * SETTLEMENT_WINDOW_MS.
     *
     * The cost is roughly 2.5x the status calls per QR (a 180 s window goes from
     * ~36 to ~90). That is the trade being made, deliberately: a cancel button that
     * usually works is worth more than the saved requests.
     */
    public static final long POLL_INTERVAL_MS = 2_000L;

    // -------------------------------------------------------------------------
    // Acquirer commission
    //
    // commissionAmount is the acquirer's cut of a sale, in fils: the merchant is
    // credited amount − commissionAmount, and the QR carries the split so
    // settlement and any later return reverse the same figures.
    //
    // This POS has no commission model — there is no operator input for it and no
    // merchant agreement behind it — so it generates every QR at zero. The field
    // is still sent explicitly rather than omitted: the gateway defaults a missing
    // commissionAmount to 0, but stating it keeps the request self-describing and
    // gives a single place to change if this terminal ever earns a commission.
    //
    // Whatever is sent here must come back on the return, which is why the value
    // rides the intent chain from generate to the success screen rather than being
    // re-derived. See ReturnApi.Call#commissionFils.
    // -------------------------------------------------------------------------

    /** Commission applied to a QR generated by this terminal, in fils. */
    public static final long QR_COMMISSION_AMOUNT = 0L;

    // -------------------------------------------------------------------------
    // The cancel window
    //
    // CANCEL is only accepted while the original transaction is UNSETTLED:
    //
    //   422 VALIDATION_ERROR {"field":"originalTransactionId"}
    //       "CANCEL is only allowed within the pre-settlement cancel window
    //        of the original transaction"
    //
    // QA settles a P2M payment about ten seconds after it is created. Measured on
    // one transaction, 2026-08-14:
    //   createdAt 19:37:01.320Z -> settledAt 19:37:11.367Z  (10.047 s)
    // A cancel that reached the gateway 88 ms after settledAt was refused, so the
    // cutoff is genuinely the settlement instant and not a grace period around it.
    //
    // ONE data point. Treat SETTLEMENT_WINDOW_MS as an estimate for the countdown
    // only — never as permission. Authority is the transaction's own
    // settlementStatus, which the history response carries; see isSettled.
    //
    // The window is measured from the gateway's createdAt, NOT from when polling
    // noticed the payment. Those differ by up to POLL_INTERVAL_MS, and anchoring to
    // detection is what caused the 88 ms miss: the countdown began 5.57 s into a
    // 10 s window and showed the operator ten seconds that were not there.
    // -------------------------------------------------------------------------

    /** Observed delay between a P2M payment being created and settled. */
    public static final long SETTLEMENT_WINDOW_MS = 10_000L;

    /**
     * Stop offering CANCEL this far before settlement is predicted.
     *
     * Covers the request's own flight time plus the error in a window estimated
     * from a single sample. Without it the POS offers a button whose call arrives
     * after the cutoff, which is a worse experience than not offering it at all.
     */
    public static final long CANCEL_SAFETY_MARGIN_MS = 1_500L;

    /** True when the gateway reports this transaction as settled — cancel is over. */
    public static boolean isSettled(JSONObject tx) {
        return "SETTLED".equals(tx.optString("settlementStatus", ""));
    }

    /**
     * The {@link android.os.SystemClock#elapsedRealtime()} value at which the POS
     * must stop offering CANCEL, or 0 when it must not be offered at all.
     *
     * Derived from the transaction's own {@code createdAt} so the countdown
     * reflects the real remaining window rather than the moment we happened to
     * notice the payment. Returns 0 — no cancel — whenever the answer cannot be
     * trusted: already settled, no parseable createdAt, or the window is spent.
     * Offering nothing is strictly better than offering a button that fails.
     *
     * @param nowElapsed elapsedRealtime() sampled alongside this call
     */
    public static long cancelDeadlineElapsed(JSONObject tx, long nowElapsed) {
        if (isSettled(tx)) return 0L;

        long createdAt = parseIsoUtc(tx.optString("createdAt", ""));
        if (createdAt <= 0) return 0L;

        // Wall clock is unavoidable here: it is the only clock shared with the
        // gateway. A device running behind the server would over-report the
        // remaining window, so clamp a negative age to zero rather than trusting it.
        long ageMs = System.currentTimeMillis() - createdAt;
        if (ageMs < 0) ageMs = 0L;

        long remaining = SETTLEMENT_WINDOW_MS - CANCEL_SAFETY_MARGIN_MS - ageMs;
        return remaining <= 0L ? 0L : nowElapsed + remaining;
    }

    // -------------------------------------------------------------------------
    // POS amount bounds
    //
    // The terminal refuses out-of-range amounts locally so no QR is ever shown
    // for a sale the gateway would reject. These are POS-side guards, not the
    // authoritative limits: the environment's configured minimum and maximum are
    // still to be confirmed (MIT-4854 Test Data lists POS_AMOUNT_MIN and
    // POS_AMOUNT_MAX_CONFIGURED as "<confirm with environment>"). Once known,
    // replace these two values — nothing else needs to change.
    //
    // MAX_INTEGER_DIGITS caps the keypad itself so an operator cannot type a
    // value long enough to lose precision in the double→fils conversion before
    // the range check ever runs.
    // -------------------------------------------------------------------------

    /** Smallest sale the POS will send, in fils (AED 0.01). */
    public static final long MIN_AMOUNT_FILS = 1L;

    /** Largest sale the POS will send, in fils (AED 100,000.00). */
    public static final long MAX_AMOUNT_FILS = 10_000_000L;

    /** Digits allowed before the decimal point on the keypad. */
    public static final int MAX_INTEGER_DIGITS = 6;

    /** Formats a fils amount as major-unit AED, for operator-facing messages. */
    public static String filsToAedText(long fils) {
        return String.format(Locale.US, "%.2f", fils / 100.0);
    }

    private static final long MIN_QR_TTL_MS = 30_000L;
    private static final long MAX_QR_TTL_MS = 900_000L;

    // Endpoints (no LFI ID embedded)
    public static final String QR_ENDPOINT        = "/lfi-gateway/api/v1/qr/generate";
    public static final String QR_STATUS_ENDPOINT = "/lfi-gateway/api/v1/transactions/history";
    public static final String RETURN_ENDPOINT    = "/lfi-gateway/api/v1/transactions/return/";
    public static final String AUTH_ENDPOINT       = "/web/api/v1/auth/login";

    // -------------------------------------------------------------------------
    // Per-environment values
    // -------------------------------------------------------------------------

    public static String getXLfiId() {
        return getXLfiId(PreferencesUtil.getEnv());
    }

    public static String getXLfiId(String env) {
        if ("staging".equals(env)) return "acq-NEOPAY";
        if ("demo".equals(env))    return "acq-NEOPAY";
        if ("qa".equals(env) || "test".equals(env)) return "acq-NI";
        return "lfi-ADCB";
    }

    public static String getDefaultWalletId() {
        return getDefaultWalletId(PreferencesUtil.getEnv());
    }

    /**
     * The merchant's TECHNICAL wallet (CUAE prefix, Central Bank layer).
     *
     * QR generation routes on this wallet, NOT on the merchant's
     * MERCHANT_COLLECTION wallet. Technical wallet = routing address;
     * collection wallet = settlement account.
     *
     * ---------------------------------------------------------------------
     * THIS IS ENVIRONMENT DATA, NOT A CONSTANT.
     *
     * QA is periodically rebuilt and every wallet in it is destroyed. When
     * that happens this id stops resolving and EVERY QR fails, with no code
     * change on our side. It has already happened twice:
     *   CUAE2DFD30048E → CUAEBBEFEB2B02 → CUAECA69D6D9C7 (current)
     *
     * Do not debug the app first. Read the error:
     *
     *   HTTP 401                                  → API key. ApiKeyManager
     *                                               self-heals; if it does not,
     *                                               the operator login failed.
     *   HTTP 400 "Acquirer QR must be generated
     *            for the merchant's technical
     *            wallet"                          → wallet EXISTS but is the
     *                                               wrong type (you used the
     *                                               NIXX collection wallet).
     *   HTTP 400 "Validation failed" (generic)    → wallet DOES NOT EXIST.
     *                                               QA was rebuilt. Fix below.
     *
     * The generic-vs-specific distinction is the whole diagnosis: a wallet of
     * the wrong type still resolves, so it gets the specific message. The
     * generic one means lookup found nothing.
     *
     * ---------------------------------------------------------------------
     * TO FIND THE NEW VALUE
     *
     * Technical wallets are NOT returned by the LFI-scoped wallet list —
     * X-LFI-ID restricts results to the LFI's own NIXX wallets and hides every
     * CUAE one. Omit that header to query the Central Bank layer:
     *
     *   TOKEN=$(curl -s -X POST \
     *     https://mithril-qa-backend.takamul.cc/web/api/v1/auth/login \
     *     -H 'Content-Type: application/json' \
     *     -d '{"username":"test-global-admin","password":"12345","realm":"cbuae"}' \
     *     | python3 -c 'import json,sys;print(json.load(sys.stdin)["access_token"])')
     *
     *   curl -s -H "Authorization: Bearer $TOKEN" \
     *     'https://mithril-qa-backend.takamul.cc/web/api/v1/wallets?walletType=TECHNICAL'
     *
     * Pick a CUAE id and confirm it before shipping:
     *
     *   curl -s -X POST "https://mithril-qa-backend.takamul.cc\
     *   /lfi-gateway/api/v1/qr/generate?requestId=$(uuidgen)" \
     *     -H 'X-LFI-ID: acq-NI' -H "X-LFI-API-KEY: <key>" \
     *     -H 'Content-Type: application/json' \
     *     -d '{"messageTypeId":"cbdc.231.101.01","qrType":"DYNAMIC",
     *          "walletId":"CUAE...","amount":5000,"currency":"AED",
     *          "terminalId":"TERM001"}'
     *
     * Requires Cloudflare WARP with a live Access session — note that the
     * tunnel being up does NOT mean the session is authenticated; an expired
     * session shows up as a 302 to cloudflareaccess.com.
     *
     * NOTE: creating a new merchant is NOT the fix and is not available to this
     * account. POST /web/api/v1/merchants 403s for the cbuae CB admin because
     * the acquirer is taken from the Keycloak session, not X-LFI-ID; it needs
     * an acq-NI realm session with MSP_ADMIN. Reuse an existing technical
     * wallet instead.
     *
     * ---------------------------------------------------------------------
     * NO REBUILD REQUIRED
     *
     * Settings > Wallet ID overrides this value at runtime — see
     * QRPayActivity#generateQR and NFCPayActivity#generateQRAndOpenHce, which both
     * fall back here only when the pref is empty. Prefer the pref for a QA
     * repoint; update this constant so fresh installs get a working default.
     *
     * Current value verified against qr/generate on 2026-08-10 —
     * merchant "Sujan Fruits and Vegetables", MCC 5411.
     * Spare, also verified the same day: CUAE265185629C
     * ("London Dairy Milk Products", MCC 5451).
     */
    public static final String QA_TECHNICAL_WALLET_ID = "CUAECA69D6D9C7";

    public static String getDefaultWalletId(String env) {
        if ("staging".equals(env)) return "NEOP979F8901FC";
        if ("demo".equals(env))    return "NEOP15B3159B17";
        if ("qa".equals(env) || "test".equals(env)) return QA_TECHNICAL_WALLET_ID;
        return "ADCB1920276ECD";
    }

    /** Regen endpoint embeds the LFI ID. */
    public static String getRegenEndpoint() {
        return "/web/api/v1/lfis/" + getXLfiId() + "/inbound-api-config/regenerate";
    }

    // -------------------------------------------------------------------------
    // Response helpers
    // -------------------------------------------------------------------------

    /**
     * Pulls the EMV QR payload out of a /qr/generate response.
     *
     * The gateway renamed this field from {@code emvPayload} to {@code emvCode}
     * (Mithril 5.x — see AcquirerQrGenerateResponse). Older envs may still send
     * the old name, so accept either.
     */
    public static String emvFrom(JSONObject json) throws JSONException {
        String emv = json.optString("emvCode", "");
        if (emv.isEmpty()) emv = json.optString("emvPayload", "");
        if (emv.isEmpty()) throw new JSONException("response has neither emvCode nor emvPayload");
        return emv;
    }

    /**
     * Reads a counterparty wallet id out of a history transaction.
     *
     * The two environments disagree on shape. Demo returns the wallets flat on
     * the transaction; QA (verified against the live QA history on 2026-08-11)
     * omits them entirely and carries them inside a {@code movements[]} array:
     *
     * <pre>
     * { "transactionId": "...", "transactionType": "PAY_TO_MERCHANT",
     *   "movements": [ { "payerWalletId": "FABX...", "payerWalletType": "RETAIL",
     *                    "payeeWalletId": "CUAE...", "payeeWalletType": "TECHNICAL" } ] }
     * </pre>
     *
     * Reading only the flat field yields an empty string on QA, which shows up as
     * "From: —" in the list and — far worse — sends an empty wallet id in a
     * refund. Prefer the flat field so demo is untouched, then fall back to the
     * first movement.
     *
     * @param field either {@code payerWalletId} or {@code payeeWalletId}
     */
    public static String walletFrom(JSONObject tx, String field) {
        String flat = tx.optString(field, "");
        if (!flat.isEmpty()) return flat;
        JSONArray movements = tx.optJSONArray("movements");
        if (movements == null || movements.length() == 0) return "";
        JSONObject first = movements.optJSONObject(0);
        return first == null ? "" : first.optString(field, "");
    }

    /**
     * The refund/cancel entries attached to a history transaction.
     *
     * QA (Mithril 5.x, TransactionRecordDto verified 2026-08-14) calls this array
     * {@code returns}, because it now holds both REFUND and CANCEL rows. Demo still
     * calls it {@code refunds}. Reading only the old name means QA never reports a
     * transaction as already returned, so the Refund button stays live on a
     * transaction that has already been refunded — a double-refund invitation.
     */
    public static JSONArray returnsOf(JSONObject tx) {
        JSONArray returns = tx.optJSONArray("returns");
        return returns != null ? returns : tx.optJSONArray("refunds");
    }

    /** Status of one {@link #returnsOf} entry — {@code status} on QA, {@code refundStatus} on demo. */
    public static String returnStatusOf(JSONObject entry) {
        String status = entry.optString("status", "");
        return status.isEmpty() ? entry.optString("refundStatus", "") : status;
    }

    /** Id of the transaction a return created — {@code returnTransactionId} on QA. */
    public static String returnTxIdOf(JSONObject entry) {
        String id = entry.optString("returnTransactionId", "");
        return id.isEmpty() ? entry.optString("refundTransactionId", "") : id;
    }

    /**
     * The acquirer commission carried on a transaction, in fils.
     *
     * QA reports it under {@code settlement}, which only appears once the sale has
     * settled; before that there is nothing to read and 0 is the honest answer for
     * a terminal that generates every QR at {@link #QR_COMMISSION_AMOUNT}. Prefer
     * the commission the QR was generated with when the caller still has it — this
     * is the fallback for a transaction read back out of history.
     */
    public static long commissionFrom(JSONObject tx) {
        JSONObject settlement = tx.optJSONObject("settlement");
        if (settlement != null) return settlement.optLong("commissionAmount", 0L);
        return tx.optLong("commissionAmount", 0L);
    }

    /**
     * OkHttp client for gateway calls.
     *
     * Redirects are off on purpose: every *.takamul.cc backend sits behind
     * Cloudflare Access, and a device without WARP gets a 302 to the Access login
     * page. Following it would return HTML with a 200, which then fails JSON
     * parsing and looks like a malformed gateway response. Leaving the 302 intact
     * lets the caller report the real cause. No gateway API legitimately redirects.
     */
    public static OkHttpClient newHttpClient() {
        return new OkHttpClient.Builder()
            .followRedirects(false)
            .followSslRedirects(false)
            .build();
    }

    /**
     * True when a response body is a Cloudflare Access / WARP gate page rather
     * than anything the gateway produced.
     */
    public static boolean looksLikeAccessGate(String responseBody) {
        if (responseBody == null || responseBody.isEmpty()) return false;
        String head = responseBody.length() > 512 ? responseBody.substring(0, 512) : responseBody;
        String lower = head.toLowerCase(Locale.US);
        return lower.contains("warp client")
            || lower.contains("cloudflare access")
            || lower.contains("cloudflareaccess.com")
            || lower.startsWith("<!doctype")
            || lower.startsWith("<html");
    }

    /**
     * How long the gateway says this QR stays valid, in ms.
     *
     * Derived from the response's own {@code expiresAt - generatedAt} pair rather
     * than from the device clock, so a POS with a skewed clock still counts down
     * the right amount. The gateway currently grants 180s while QR_TIMEOUT_MS is
     * 300s — counting down the local constant leaves a dead QR on screen for two
     * minutes. Falls back to QR_TIMEOUT_MS if the timestamps are missing.
     */
    public static long ttlMsFrom(JSONObject json) {
        long generatedAt = parseIsoUtc(json.optString("generatedAt", ""));
        long expiresAt   = parseIsoUtc(json.optString("expiresAt", ""));
        if (generatedAt > 0 && expiresAt > generatedAt) {
            long ttl = expiresAt - generatedAt;
            // Guard the countdown UI against an implausible window.
            if (ttl >= MIN_QR_TTL_MS && ttl <= MAX_QR_TTL_MS) return ttl;
        }
        return QR_TIMEOUT_MS;
    }

    /**
     * Parses the gateway's ISO-8601 UTC timestamps, e.g.
     * {@code 2026-07-30T07:47:59.645825943Z}. Returns -1 when unparseable.
     *
     * Fractional seconds are dropped: they carry nanosecond precision, which
     * SimpleDateFormat cannot read, and second precision is enough for a timer.
     * SimpleDateFormat is used rather than java.time because minSdk is 25.
     */
    public static long parseIsoUtc(String timestamp) {
        if (timestamp.length() < 19) return -1;
        try {
            SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss", Locale.US);
            fmt.setTimeZone(TimeZone.getTimeZone("UTC"));
            Date parsed = fmt.parse(timestamp.substring(0, 19));
            return parsed == null ? -1 : parsed.getTime();
        } catch (ParseException e) {
            return -1;
        }
    }

    /**
     * Human-readable text for a failed gateway call.
     *
     * Errors come back as {@code {"code":"AUTH_TOKEN_MISSING","defaultMessage":"..."}},
     * which is far more useful on the POS screen than a bare status code.
     */
    public static String errorTextOf(String responseBody, int httpCode) {
        if (looksLikeAccessGate(responseBody)) {
            return "blocked by Cloudflare Access — connect the WARP client on this device";
        }
        try {
            JSONObject json = new JSONObject(responseBody);
            String msg  = json.optString("defaultMessage", json.optString("message", ""));
            String code = json.optString("code", "");
            if (!msg.isEmpty()) {
                return code.isEmpty() ? msg : msg + " (" + code + ")";
            }
        } catch (Exception ignored) {
            // Not JSON (e.g. a Cloudflare Access redirect body) — fall through.
        }
        return "HTTP " + httpCode;
    }

    public static String getBaseUrl() {
        switch (PreferencesUtil.getEnv()) {
            case "dev":   return "https://mithril-dev-backend.takamul.cc";
            case "qa":
            case "test":  return "https://mithril-qa-backend.takamul.cc";
            case "local": return "http://localhost:3000";
            case "demo":  return "https://mithril-demo-backend.takamul.cc";
            case "staging":
            default:      return "https://mithril-staging-backend.takamul.cc";
        }
    }
}
